WebApplication5/Controllers/RegisterUserController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class RegisterUserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public RegisterUserController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(UserSignUpViewModel p)
        {
            if(ModelState.IsValid)
            {
                AppUser user = new AppUser()
                {
                    Email = p.Mail,
                    name = p.Name,
                    UserName = p.Username
                };
                var result = await _userManager.CreateAsync(user,p.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Login", "Account");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }

                }
            }
            
            return View(p);
        }
    }
}

WebApplication5/Views/RegisterUser/Index.cshtml
@model UserSignUpViewModel
@{
    Layout = null;
}
<head>
    <!-- Basic need -->
    <title>Open Pediatrics</title>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <link rel="profile" href="#">

    <!--Google Font-->
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />
    <!-- Mobile specific meta -->
    <meta name=viewport content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone-no">

    <!-- CSS files -->
    <link rel="stylesheet" href="~/template2/css/deneme.css">
    <link rel="stylesheet" href="~/template2/css/plugins.css">
    <link rel="stylesheet" href="~/template2/css/style.css">
    @*<link rel="stylesheet" href="~/template2/css/style.css">*@

</head>
@*
<div>
    <h3>Kayıt Ekranı</h3>
    <form class="m-t" role="form" asp-action="Index">
        <div class="form-group">
            <input type="text" class="form-control" asp-for="@Model.Name" placeholder="Ad Soyad" required="" />
        </div>
        <br />
        <div class="form-group">
            <input type="text" class="form-control" asp-for="@Model.Username" placeholder="Kullanıcı adı" required="" />
        </div>
        <br />
        <div class="form-group">
            <input type="email" class="form-control" asp-for="@Model.Mail" placeholder="Email" required="" />
        </div>
        <br />
        <div class="form-group">
            <input type="password" class="form-control" asp-for="@Model.Password" placeholder="Şifre" required="" />
        </div>
        <br />
        <div class="form-group">
            <input type="password" class="form-control" asp-for="@Model.ConfirmPassword" placeholder="Şifre tekrar" required="" />
        </div>
        <br />
    </form>
    <button type="submit" class="btn btn-primary block full-width m-b">Kayıt ol</button>
    <p class="text-muted text-center"><small>Bir hesabınız var mı?</small></p>
    <a class="btn btn-sm btn-white btn-block" href="/Login/Index">Giriş Yap</a>
</div>
*@


<body>

    <div class="log-form">
        <h2>Kayıt Ol</h2>
        @using (Html.BeginForm("Index", "RegisterUser", FormMethod.Post))
        {
            <div class="form-row">
                <label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Adınızı girin" })
                    <span asp-validation-for="@Model.Name" class="text-danger" style="color: red;"></span>
                </label>
            </div>
            <div class="form-row">
                <label>
                    @Html.TextBoxFor(x => x.Username, new { @class = "form-control", placeholder = "Kullanıcı adınızı girin"  })
                    <span asp-validation-for="@Model.Username" class="text-danger" style="color: red;"></span>
                </label>
            </div>

            <div class="form-row">
                <label>
                    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control", placeholder = "Mail adresi girin"  })
                    <span asp-validation-for="@Model.Mail" class="text-danger" style="color: red;"></span>
                </label>
            </div>
            <div class="form-row">
                <label>
                    @Html.PasswordFor(x => x.Password, new { @class = "form-control", placeholder = "Şifrenizi girin"  })
                    <span asp-validation-for="@Model.Password" class="text-danger" style="color: red;"></span>
                </label>
            </div>
            <div class="form-row">
                <label>
                    @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "form-control", placeholder = "Şifrenizi tekrar girin"   })
                    <span asp-validation-for="@Model.ConfirmPassword" class="text-danger" style="color: red;"></span>
                </label>
            </div>
            <button type="submit" class="btn">Kayıt Ol</button>
            <a class="forgot" href="#">Giriş Yap</a>
            <div class="text-danger" style="color: red;" asp-validation-summary="ModelOnly">
            </div>
        }
    </div>
</body>
@*
<div class="page-single">
    <div class="wrapper">
        <h2>Registration</h2>
        <form action="/RegisterUser/Index" method="post">
            <div class="form-row">
                <label for="validationCustom01">
                    <h6>Name Surname:</h6>
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    <input type="text" class="form-control" name="Name" value="" />
                </label>
            </div>
            <div class="form-row">
                <label for="validationCustom02">
                    <h6>Username:</h6>
                    <input type="text" class="form-control" name="Username" value="" />
                    <span class="text-danger">Hata Mesajı</span>
                </label>
            </div>

            <div class="form-row">
                <label for="email-2">
                    <h6>Your Email:</h6>
                    <span asp-validation-for="@Model.Mail" class="text-danger"></span>
                    <input type="text" class="form-control" name="Mail" value="" />
                </label>
            </div>
            <div class="form-row">
                <label for="password-2">
                    <h6>Password:</h6>
                    <input type="password" class="form-control" name="Password" value="" />
                    <span class="text-danger">Hata Mesajı</span>
                </label>
            </div>
            <div class="form-row">
                <label for="repassword-2">
                    <h6>Re-type Password:</h6>
                    <input type="password" class="form-control" name="ConfirmPassword" value="" />
                    <span class="text-danger">Hata Mesajı</span>
                </label>
            </div>
            <div class="row">
                <button type="submit">Sign Up</button>
            </div>
        </form>
    </div>
</div>
*@